### PR TITLE
Unimos todo 

### PR DESCRIPTION
**Pull request by SofiDubrowsky**
que se yo

### CODE REVIEW

**Review by JuanPabloMora61 — DISMISSED** [review]

**Review by FabriVettorelo — APPROVED** [review]
10/10

**Review by Gonzasch35 — APPROVED** [review]

**Review by Gonzasch35 — APPROVED** [review]

**Review by LucianoVelasquez — APPROVED** [review]
👍

**Review by nadiamartel — APPROVED** [review]
vamooo!!!

**Comment by JuanPabloMora61** [comment]
[US1 - T1 - Crear rutas POST/ GET/ user](https://trello.com/c/j0O0O1MZ/2-us1-t1-crear-rutas-post-get-user)

**Pull request merged**
